"""add phone number

Revision ID: b99791c620b3
Revises: 5cb4a1b13153
Create Date: 2023-07-25 00:11:59.680474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99791c620b3'
down_revision = '5cb4a1b13153'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
